stages:
  - check
  - trigger

default:
  interruptible: true

workflow:
  rules:
    - if: $CI_EXTERNAL_PULL_REQUEST_IID

check_branch_existance:
  stage: check
  image: curlimages/curl
  tags: 
    - docker-prod
  variables:
    GIT_STRATEGY: none
  script:
    - TRIGGER_BRANCH=${CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME}
    - curl --fail --silent --show-error --request GET --header "PRIVATE-TOKEN:iQFxVogVMLQJyMXsCcUL" "https://main.gitlab.in.here.com/api/v4/projects/7121/repository/branches/${CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME}" || TRIGGER_BRANCH='master'
    - echo "__DEBUG__ TRIGGER_BRANCH=${TRIGGER_BRANCH}"
    - echo "TRIGGER_BRANCH=$TRIGGER_BRANCH" >> vars.env
    - |
      echo "trigger_internal_ci:
  stage: trigger
  variables:
    EXT_PULL_REQUEST_TARGET_BRANCH_NAME: $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    EXT_PULL_REQUEST_SOURCE_BRANCH_NAME: $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
    EXT_PULL_REQUEST_IID: $CI_EXTERNAL_PULL_REQUEST_IID
    TRIGGER_BRANCH: $TRIGGER_BRANCH
  trigger:
    project: zhernovs/test-sdk-6
    strategy: depend
    branch: $TRIGGER_BRANCH" > generated-config.yml
  artifacts:
    reports:
      dotenv: vars.env
    paths: 
      - vars.env
      - generated-config.yml

child-pipeline:
  stage: trigger
  trigger:
    include:
      - artifact: generated-config.yml
        job: check_branch_existance


  
# trigger_internal_ci_api:
#   stage: trigger
#   image: curlimages/curl
#   tags: 
#     - docker-prod
#   variables:
#     GIT_STRATEGY: none
#   script:
#     - curl --fail --silent --show-error --request POST --form "token=$CI_JOB_TOKEN" --form ref=${TRIGGER_BRANCH} --form strategy=depend "https://main.gitlab.in.here.com/api/v4/projects/7121/trigger/pipeline"
#   needs:
#     - job: check_branch_existance
#       artifacts: true 

# trigger_internal_ci:
#   stage: trigger
#   variables:
#     EXT_PULL_REQUEST_TARGET_BRANCH_NAME: $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
#     EXT_PULL_REQUEST_SOURCE_BRANCH_NAME: $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
#     EXT_PULL_REQUEST_IID: $CI_EXTERNAL_PULL_REQUEST_IID
#     TRIGGER_BRANCH: $TRIGGER_BRANCH
#   trigger:
#     project: zhernovs/test-sdk-6
#     strategy: depend
#     # Until we can use this: https://docs.gitlab.com/ee/ci/variables/README.html#inherit-environment-variables it will fail if no such branch in downstream project
# #    branch: "$TRIGGER_BRANCH"
#     branch: feature-12
#   needs:
#     - job: check_branch_existance
#       artifacts: true  
  
#test_inherited_var_feature:
#  stage: trigger
#  script:
#    - echo "VAR $TRIGGER_BRANCH" 
#  needs:
#    - job: check_branch_existance
#      artifacts: true  
