check_vars:
  image: ubuntu
  tags:
    - docker-prod
  script:
    - echo "Environment variables"
    - env
  only:
    - external_pull_requests


trigger_internal_ci:
  variables:
    EXT_PULL_REQUEST_TARGET_BRANCH_NAME: $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    EXT_PULL_REQUEST_SOURCE_BRANCH_NAME: $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
    EXT_PULL_REQUEST_IID: $CI_EXTERNAL_PULL_REQUEST_IID
  trigger:
    project: zhernovs/test-sdk-6
    strategy: depend
    # Until we can use this: https://gitlab.com/gitlab-org/gitlab/-/issues/22638 it will fail if no such branch in downstream project
    branch: $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
  only:
    - external_pull_requests
