name: Generate Docs

on:
    workflow_dispatch

env:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    GECKODRIVER_SKIP_DOWNLOAD: true
    CHROMEDRIVER_SKIP_DOWNLOAD: true


jobs:
    docs:
        name: Generate Docs
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v2
        - run: yarn --frozen-lockfile
        - run: yarn docs           
